version: '3.8'

services:
  flow2api:
    build:
      context: .
      dockerfile: Dockerfile
    image: flow2api:local
    container_name: flow2api
    ports:
      - "38000:8000"
    volumes:
      - ./data:/app/data
      - ./config/setting.toml:/app/config/setting.toml
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOW_DOCKER_BROWSER_CAPTCHA=1
    shm_size: "1gb"
    restart: unless-stopped
