version: '3.8'

services:
  flow2api:
    image: thesmallhancat/flow2api:latest
    container_name: flow2api
    ports:
      - "38000:8000"
    volumes:
      - ./data:/app/data
      - ./config/setting_warp.toml:/app/config/setting.toml
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOW_DOCKER_BROWSER_CAPTCHA=1
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      - warp

  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "31080:1080"
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
